# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{ config, lib, pkgs, modulesPath, ... }:

{
  imports =
    [ (modulesPath + "/installer/scan/not-detected.nix")
    ];

  boot.initrd.availableKernelModules = [ "nvme" "xhci_pci" "usbhid" "usb_storage" "sd_mod" ];
  boot.initrd.kernelModules = [ ];
  boot.kernelModules = [ "kvm-amd" ];
  boot.extraModulePackages = [ ];

  fileSystems."/" =
    { device = "/dev/disk/by-uuid/6552e676-ea57-4c2b-a209-480f8533d09e";
      fsType = "btrfs";
      options = [ "subvol=@" "noatime" "compress=zstd" ];
    };

  fileSystems."/data" =
    { device = "/dev/disk/by-uuid/6552e676-ea57-4c2b-a209-480f8533d09e";
      fsType = "btrfs";
      options = [ "subvol=@data" "noatime" "compress=zstd" ];
    };

  fileSystems."/home" =
    { device = "/dev/disk/by-uuid/6552e676-ea57-4c2b-a209-480f8533d09e";
      fsType = "btrfs";
      options = [ "subvol=@home" "noatime" "compress=zstd" ];
    };

  fileSystems."/nix" =
    { device = "/dev/disk/by-uuid/6552e676-ea57-4c2b-a209-480f8533d09e";
      fsType = "btrfs";
      options = [ "subvol=@nix" "noatime" "compress=zstd" ];
    };

  fileSystems."/var/lib" =
    { device = "/dev/disk/by-uuid/6552e676-ea57-4c2b-a209-480f8533d09e";
      fsType = "btrfs";
      options = [ "subvol=@lib" "noatime" "compress=zstd" ];
    };

  fileSystems."/var/log" =
    { device = "/dev/disk/by-uuid/6552e676-ea57-4c2b-a209-480f8533d09e";
      fsType = "btrfs";
      options = [ "subvol=@log" "noatime" "compress=zstd" ];
    };

  fileSystems."/boot" =
    { device = "/dev/disk/by-uuid/546D-E508";
      fsType = "vfat";
      options = [ "fmask=0022" "dmask=0022" ];
    };

  swapDevices = [ ];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
